manifest:
  version: "0.10"
  projects:

    # Specify the nRF-Connect SDK as a project dependency.
    - name: sdk-nrf
      path: nrf
      url: https://github.com/nrfconnect/sdk-nrf.git
      revision: v2.6.0
      import:
        name-allowlist:
          - hostap
          - zephyr
          - mcuboot
          - mbedtls
          - nrfxlib
          - cmsis
          - hal_nordic
