manifest:
  version: "0.10"
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: zephyr
      revision: v4.0.99
      url: https://github.com/zephyrproject-rtos/zephyr
