manifest:
  version: "0.10"
  remotes:
    - name: origin
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      revision: v4.0.0
      url: https://github.com/zephyrproject-rtos/zephyr

