name: Build Black Magic Probe Firmware

on:
  push:
    branches:
      - Debugger
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ARM GCC Toolchain and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libusb-1.0-0-dev \
            libhidapi-dev \
            libftdi1-dev \
            meson \
            ninja-build \
            pkg-config

      - name: Configure Build for STM32F103C8
        run: |
          cd firmware # Adjust this path
          meson setup builddir \
            --cross-file=../cross-file.txt \ # Adjust if cross-file is not in root
            -Dplatform=swlink

      - name: Build Firmware
        run: |
          cd firmware # Adjust this path
          meson compile -C builddir

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: blackmagic-firmware
          path: firmware/builddir/src/blackmagic.bin

