name: Build Black Magic Probe Firmware

on:
  push:
    branches:
      - Debugger
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build meson gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Clone Black Magic Probe Repository
      run: |
        git clone --recursive https://github.com/blackmagic-debug/blackmagic.git
        cd blackmagic

    - name: Configure Build for STM32F103C8 (Blue Pill)
      working-directory: blackmagic
      run: |
        meson setup build --cross-file cross-file/bluepill.ini -Dprobe=bluepill -Dtargets=cortexm,stm -Drtt_support=false

    - name: Compile Firmware
      working-directory: blackmagic
      run: |
        meson compile -C build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bmp-firmware
        path: blackmagic/build/*.bin


