name: Build

on:
  pull_request:
  push:
    branches:
      - Bootloader
  repository_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:

          - 'revolute'
          - 'revoluteWireless'
          - 'feather_nrf52832'
             
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2' 


    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Checkout linkermap
      uses: actions/checkout@v4
      with:
         repository: hathach/linkermap
         path: linkermap

    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10-2020-q4'

    - name: Install Tools
      run: |
        pip3 install adafruit-nrfutil uritemplate requests intelhex setuptools
        pip3 install linkermap/

    - name: Build
      run: |
        arm-none-eabi-gcc --version
        make --version
        python3 --version
        make BOARD=${{ matrix.board }} all
        make BOARD=${{ matrix.board }} copy-artifact

    - name: Linker Map
      run: make BOARD=${{ matrix.board }} linkermap

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.board }}
        path: _bin/${{ matrix.board }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: ${{ github.event_name == 'release' }}
      with:
        files: |
          _bin/${{ matrix.board }}/${{ matrix.board }}_bootloader-*.zip
          _bin/${{ matrix.board }}/${{ matrix.board }}_bootloader-*.hex
          _bin/${{ matrix.board }}/update-${{ matrix.board }}_bootloader-*.uf2
