name: Build Black Magic Probe Firmware

on:
  push:
    branches:
      - Debugger
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: blackmagic-debug/blackmagic
        path: blackmagic
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi stm32flash dfu-util

    - name: Build Firmware
      working-directory: ./blackmagic
      run: |
        make PROBE_HOST=swlink

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: blackmagic-firmware
        path: ./blackmagic/src/blackmagic
